- efsity/README.md
> Add instructions to persist alias on terminal reload

- efsity/src/main/java/org/smartregister/command/ValidateFhirResourcesCommand.java
fixes #https://github.com/onaio/fhir-tooling/issues/94
> Print config errors

- efsity/README.md
- efsity/build.gradle.kts
- efsity/src/main/java/org/smartregister/command/PublishFhirResourcesCommand.java
- efsity/src/main/java/org/smartregister/command/ValidateFhirResourcesCommand.java
- efsity/src/test/java/org/smartregister/command/PublishFhirResourcesCommandTest.java
fixes https://github.com/onaio/fhir-tooling/issues/87
> Validate FHIR Resources before publishing.

- importer/README.md
- importer/csv/locations/locations_full.csv
- importer/json_payloads/locations_payload.json
- importer/main.py
> 115 add physical type

- importer/README.md
- importer/csv/careteams/careteam_full.csv
- importer/csv/organizations/organizations_full.csv
- importer/main.py
> 117 remove version

- importer/json_payloads/locations_payload.json
- importer/main.py
- importer/test_main.py
> 122 generate unique UUID

- importer/README.md
- importer/main.py
Use click progress bar to show progress for csv read and building payload
Fixes #141 
> Add progress bar

- importer/README.md
- importer/main.py
> Print final response

- importer/README.md
- importer/main.py
- importer/test_main.py
> 129 export resource uuids

- importer/README.md
- importer/csv/organizations/organizations_min.csv
- importer/main.py
- importer/test_main.py
> Fix organizations_min.csv, locations_min.csv and  careteam_min.csv build payload

- importer/csv/locations/locations_full.csv
- importer/json_payloads/locations_payload.json
- importer/main.py
- importer/test_main.py
> Add optional geometry to location

- importer/main.py
- importer/requirements.txt
- importer/sample_config.py
> save image as binary resource

- importer/README.md
- importer/csv/locations/locations_full.csv
- importer/json_payloads/locations_payload.json
- importer/main.py
- importer/test_main.py
> Add Admin Level to each locations payload

- importer/README.md
- importer/csv/import/inventory.csv
- importer/csv/import/product.csv
- importer/json_payloads/inventory_group_payload.json
- importer/json_payloads/product_group_payload.json
- importer/main.py
- importer/test_main.py
Part of #157 
Built this branch off of #178 so it might look a bit more loaded 
> Add support for importing inventory and products

- importer/README.md
- importer/csv/import/inventory.csv
- importer/json_payloads/inventory_location_list_payload.json
- importer/main.py
- importer/test_main.py
> 161 link location inventories

- importer/main.py
> Handle deletion of inventory identifiers properly

- importer/main.py
Fixes #230 
Also part of #210 
> Update how partOf is added to a location

- importer/README.md
- importer/json_payloads/locations_payload.json
- importer/main.py
- importer/test_main.py
> Add config option to define own location-type coding system url

- importer/README.md
- importer/importer/config/settings.py
- importer/pytest.ini
- importer/requirements.txt
Resolves https://github.com/sid-indonesia/it-team/issues/313
What this commit has achieved:
1. Renamed an entry in `.env` from `username` to `user_name` to accomodate usage within Windows OS (there is a default OS env var %username% within Windows OS)
2. Added `python-magic-bin` to the `requirements.txt`, to resolve issue of:
```
ImportError: failed to find libmagic.  Check your installation
```
(Possibly only happens in Windows OS, not really sure)
> Affected Issue(s): Fixes when try to run within Windows OS environment

- importer/README.md
- importer/importer/builder.py
- importer/requirements.txt
- importer/tests/test_builder.py
Add functionality to calculate the accountability date using the product's accountability period
Fixes #264 
> Calculate accountability end date

- uploader/uploader.sh
> [Uploader] Use jq -r to get resource type without quote

- importer/README.md
- importer/importer/users.py
These came up after a debugging session, their purpose it to help make the code clearer
1. Update docs to use .env instead of config
2. Add some logs for clarity, to show why a user was not created if the request fails
> clean fixes

- importer/importer/builder.py
- importer/main.py
> Ensure all resources are correctly added to the list resources

- linking/README.md
- linking/config.py
- linking/main.py
- linking/request.py
- linking/requirements.txt
> Add linking duplicates script

- efsity-cli/src/main/java/org/smartregister/command/QuestionnaireResponseGeneratorCommand.java
- efsity-cli/src/test/java/org/smartregister/command/QuestionnaireResponseGeneratorCommandTest.java
> Add fix for failing valueInteger
