onaio/fhir-tooling

LICENSE
README.md

add bls license

---

efsity/build.gradle.kts

New release version 2.3.3

---

efsity/src/main/java/org/smartregister/command/ValidateFhirResourcesCommand.java

Fixes https://github.com/onaio/fhir-tooling/issues/108

Fail check on invalid config

---

efsity/README.md
efsity/src/main/java/org/smartregister/command/PublishFhirResourcesCommand.java
efsity/src/main/java/org/smartregister/util/authentication/OAuthAuthentication.java

FIxes part of https://github.com/onaio/fhir-tooling/issues/79

OAuth2 support

---

cleaner/README.md
cleaner/main.py
cleaner/test_main.py

Add cascade delete to cleaner

---

importer/json_payloads/locations_payload.json
importer/main.py

Change Physical_Type to type in locations_payload.json structure

---

sm-gen/.gitignore
sm-gen/src/main/kotlin/org.smartregister.fhir.structuremaptool/Main.kt

Fixes [#195](https://github.com/onaio/opensrp-tasks/issues/195)

Generate Json version of .map file

---

sm-gen/src/main/kotlin/org.smartregister.fhir.structuremaptool/Main.kt
sm-gen/src/main/kotlin/org.smartregister.fhir.structuremaptool/Utils.kt

validates the questionnaire response item id and resource name

---

importer/json_payloads/locations_payload.json
importer/main.py

Fixes #75
The following use cases are what is implemented:
If the 'method' is == create:
- and new id is provided -> use the new id to create new resource
- and no id is provided -> generate a new id and use that to create new resource
If the 'method' is == update:
- and id existing in server is provided -> update resource with provided id
- and a new id is provided -> use the new id to create new resource
- and no id is provided -> generate a new id and use that to create new resource
Is there any case that is missing above? or anything that needs correction?
If we all agree with the above we can potentially eliminate the "method" column as well 

75 improve importer script

---

cleaner/main.py

Update delete function

---

importer/csv/locations/locations_full.csv
importer/main.py
importer/requirements.txt
importer/test_main.py

Fixes https://github.com/onaio/fhir-tooling/issues/126

Some tests for the importer

---

importer/main.py

Log to importer.log file as well as to terminal

---

efsity/build.gradle.kts

Updates Efsity version to 2.3.4

Update to Version 2.3.4

---

importer/README.md
importer/csv/practitioners/practitioner_organization.csv
importer/json_payloads/practitioner_organization_payload.json
importer/main.py
importer/test_main.py

Assign  practitioner to organization

---

importer/main.py
importer/test_main.py

Write tests for user creation 

---

importer/json_payloads/user_resources_payload.json
importer/main.py
importer/test_main.py

Add a type property on the Keycloak User Id Identifier

---

efsity/build.gradle.kts
efsity/src/main/java/org/smartregister/Main.java
efsity/src/main/java/org/smartregister/command/PublishFhirResourcesCommand.java
efsity/src/main/java/org/smartregister/command/QuestionnaireResponseGeneratorCommand.java
efsity/src/main/java/org/smartregister/command/TranslateCommand.java
efsity/src/main/java/org/smartregister/command/ValidateFhirResourcesCommand.java
efsity/src/main/java/org/smartregister/command/ValidateFileStructureCommand.java
efsity/src/main/java/org/smartregister/processor/FctValidationProcessor.java
efsity/src/main/java/org/smartregister/processor/QuestionnaireProcessor.java
efsity/src/main/java/org/smartregister/processor/StructureMapProcessor.java
efsity/src/main/java/org/smartregister/util/FCTConstants.java
efsity/src/main/java/org/smartregister/util/authentication/OAuthAuthentication.java
efsity/src/main/kotlin/org/smartregister/external/CqlToLibraryConvertServices.kt
efsity/src/main/kotlin/org/smartregister/external/FhirCarePlanGeneratorLite.kt
efsity/src/main/kotlin/org/smartregister/external/TransformSupportServices.kt
efsity/src/test/java/org/smartregister/command/PublishFhirResourcesCommandTest.java
efsity/src/test/java/org/smartregister/command/TranslateCommandTest.java
efsity/src/test/java/org/smartregister/command/ValidateFhirResourcesCommandTest.java
efsity/src/test/java/org/smartregister/command/ValidateFileStructureCommandTest.java

- Some updates to Efisty's `Publish` command implementation to make it more robust
- Configure Spotless extension to process Java files
- Spotless format all Java files

Publish FHIR Resources Command enhancements

---

efsity/src/main/java/org/smartregister/command/PublishFhirResourcesCommand.java

Update resource.meta.tag array if it exists, otherwise create a new object
Fixes #183 

FCT: Update resource.meta.tag array if it exists, otherwise create a new object

---

efsity/build.gradle.kts
efsity/src/main/java/org/smartregister/command/TranslateCommand.java
efsity/src/test/java/org/smartregister/command/PublishFhirResourcesCommandTest.java
efsity/src/test/resources/strings_fr.properties

Fix accent encoding bug

---

efsity/build.gradle.kts
efsity/src/main/java/org/smartregister/command/PublishFhirResourcesCommand.java
efsity/src/main/java/org/smartregister/util/FCTConstants.java
efsity/src/main/kotlin/org/smartregister/external/TransformSupportServices.kt
efsity/src/test/java/org/smartregister/command/PublishFhirResourcesCommandTest.java

Enhancements to i18N and Maintainability + Release 2.3.6

---

efsity/build.gradle.kts
efsity/src/main/java/org/smartregister/command/PublishFhirResourcesCommand.java
efsity/src/main/java/org/smartregister/command/TranslateCommand.java
efsity/src/test/java/org/smartregister/command/TranslateCommandTest.java
efsity/src/test/resources/strings_fr.properties

Refactor i18N fix encoding bug 🐛

---

importer/README.md
importer/json_payloads/product_list_payload.json
importer/main.py
importer/test_main.py

Create List resource referencing Group and Binary resources created by product import
Fixes #217

Create List resource to reference product resources

---

sm-gen/README.md

Add SM Tool readme file

---

efsity/src/main/kotlin/org/smartregister/external/TransformSupportServices.kt

Initial Commit - Update TransformSupportServices class

---

importer/json_payloads/locations_payload.json

deplicate physical type in location type payload

---

importer/main.py

Linked to #225 
That first PR handles adding the physical-location when present in the csv
This one handles removing the json object when absent in the csv
Also separate small fix to check for values because trying to strip() None would fail

225 - remove location-physical-type from type[] when not defined

---

importer/README.md
importer/json_payloads/group_list_payload.json
importer/main.py
importer/test_main.py

Add inventories to List

---

efsity/build.gradle.kts
efsity/libs.versions.toml
efsity/src/main/java/org/smartregister/command/PublishFhirResourcesCommand.java
efsity/src/main/java/org/smartregister/command/TranslateCommand.java
efsity/src/main/java/org/smartregister/util/FctUtils.java
efsity/src/test/java/org/smartregister/command/TranslateCommandTest.java
efsity/src/test/resources/dirty_configs_folder/profile_config.json

Efsity | Character encoding auto-detection for properties files

---

importer/main.py

Fix indentation bug in the process_chunk function

---

.github/workflows/ci.yml
efsity/README.md
efsity/build.gradle.kts
efsity/docs/QuestionnaireResponseGenerator.md
efsity/libs.versions.toml
efsity/src/main/java/org/smartregister/command/QuestionnaireResponseGeneratorCommand.java
efsity/src/main/java/org/smartregister/util/HttpClient.java
efsity/src/test/java/org/smartregister/command/QuestionnaireResponseGeneratorCommandTest.java

Use $populate operation to generate questionnaireResponse

---

uploader/uploader.sh

[Uploader] Check if jq is installed

---

uploader/README.md

[Uploader] Add doc for jq dependency

---

importer/importer/utils.py

Use get_keycloak_url in utils

---

importer/csv/setup/roles.csv

Add new OpenSRP web roles

---

efsity/build.gradle.kts
efsity/src/main/java/org/smartregister/command/QuestionnaireResponseGeneratorCommand.java

- Hot fix - random number generator using incorrect bound value
- Release version 2.3.10

Hotfix - Random Number Generator Bug

---

efsity/build.gradle.kts
efsity/src/main/java/org/smartregister/command/QuestionnaireResponseGeneratorCommand.java

Add troubleshooting snapshot

---

efsity-cli/build.gradle.kts

Create new release snapshot

---

efsity-cli/README.md
efsity-cli/build.gradle.kts
efsity-cli/src/main/java/org/smartregister/Main.java
efsity-cli/src/main/java/org/smartregister/command/UpdateLocationLineageCommand.java
efsity-cli/src/test/java/org/smartregister/command/UpdateLocationLineageCommandTest.java

Update location lineage tags

---

efsity-cli/.gitignore
efsity-cli/build.gradle.kts

Update the ignore file correctly
